import React,{useEffect} from 'react'
import Header from "../../component/Header"
import Footer from "../../component/Footer";


export default function DCMA(props) {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });


    return(
    <>
<Header withbg={true}  {...props} />
<div className="contactpage page pb0">
  
<div className=" imgbox  paddrem1 platformcard">
  <h2>Terms & Conditions</h2>

  <div className="container_custom container-fluid ">
    <div class="media-body media-body-2 ">
    <p align="justify">The Site(s) is operated by RTF LIVE, LLC ("us/our/we" or "RTF LIVE"). RTF LIVE provides an online platform and related services that connects buyers and sellers of goods and services and facilitates the sale of goods and services between the two, in addition to operating a live App trivia game show (collectively, the "Services"). All rights are hereby reserved with respect to our service marks, trademarks, logos, and trade dress ("Marks"). "Site(s)" means the Site(s) located at <a href="http://www.rewardthefan.com">www.rewardthefan.com</a>, and any subsequent URL which may replace any of these Site(s), and any and all associated mobile site(s) and/or application(s), including but not limited to the RTF LIVE App ("App"), and all associated website(s), URL(s) and micro site(s) provided by us. "You/your" means you as a user of the Site(s). "User" means all users of the Site(s). We offer the Site(s), including all information and services available from the Site(s), to you conditioned upon your acceptance of all of the terms, conditions, policies and notices stated herein. The RTF LIVE <a href="http://www.rewardthefan.com/Rules">Official Rules</a> and <a href="http://www.rewardthefan.com/PrivacyPolicy">Privacy Policy</a>  are part of and incorporated into these Terms of Use. </p>
    <p align="justify"><strong>YOUR CONTINUED USE OF THE SITE(S) CONSTITUTES YOUR AGREEMENT TO THESE TERMS OF USE.</strong> </p>
    <p align="justify"><strong>YOU ACKNOWLEDGE AND AGREE THAT BY ACCESSING OR USING THE SITE(S), OR BY DOWNLOADING OR POSTING ANY CONTENT FROM OR THROUGH THE SITE(S), YOU ARE INDICATING THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THESE TERMS.</strong> </p>
    <p align="justify">If there is anything you do not understand, please email any inquiry to <a href="\&quot;mailto:info@rewardthefan.com\&quot;">info@rewardthefan.com</a>. If at any time you do not agree to these Terms of Use, please do not use the Site(s). </p>
    <p align="justify">YOU SHALL NOT USE THE SITE(S) FOR ANY ILLEGAL PURPOSES, AND YOU WILL USE IT IN COMPLIANCE WITH ALL APPLICABLE LAWS AND REGULATIONS. YOU SHALL NOT USE THE SITE(S) IN A WAY THAT MAY CAUSE THE SITE(S) TO BE INTERRUPTED, DAMAGED, RENDERED LESS EFFICIENT OR SUCH THAT THE EFFECTIVENESS OR FUNCTIONALITY OF THE SITE(S) IS IN ANY WAY IMPAIRED. YOU AGREE NOT TO ATTEMPT ANY UNAUTHORIZED ACCESS TO ANY PART OR COMPONENT OF THE SITE(S)</p>
    <p align="justify"><strong>&nbsp;1.&nbsp;<u>Eligibility.</u></strong></p>
    <p align="justify">You represent and warrant that: (i) you are at least eighteen (18) years old, or thirteen (13) years old with parental consent; (ii) you have the right, capacity and authority to be bound by these Terms, and (iii) you will abide by all these Terms.</p>
    <p align="justify"><strong>&nbsp;2.&nbsp;<u>Intellectual Property Ownership and Use.</u></strong></p>
    <p align="justify">&nbsp;2.1&nbsp;You acknowledge and agree that the Marks, copyrights and any and all other intellectual property rights in all material or content contained within the Site(s) shall remain at all times vested in us or, in the cases where we are using such material or content under authority from a third party, in the owner of such material or content.</p>
    <p align="justify">&nbsp;2.2&nbsp;We grant you the limited right to access and make use of the Site(s) as our user. However, you shall not: a) reproduce, duplicate, copy, sell or otherwise exploit the Site(s) or any image, page layout, page design, trade dress, trademark, logo or other content ("Site Content") for any commercial purpose; b) use a robot, spider or data mining or extraction tool or process to monitor, extract or copy Site Content; c) use any meta tags, search terms, key terms, or the like that contain the Site(s)'s name or our Marks; d) engage in any activity that interferes with the Site(s) or another user's ability to use the Site(s); e) modify, create derivative works from, reverse engineer, decompile or disassemble any technology used to provide the Site(s) and the goods or services offered on the Site(s); or f) assist or encourage any third party in engaging in any activity prohibited by these Terms of Use.</p>
    <p align="justify">&nbsp;2.3&nbsp;You shall not use, copy, distribute, or exploit any of the Marks or Site Content in any manner without our prior written permission. You may not link to the Site(s) from any pornographic, obscene, profane, defamatory, libelous, threatening, unlawful or other website or material which could constitute or encourage unlawful conduct that would be considered a criminal offense, give rise to civil liability, or otherwise violate any law or regulation. LINKING TO THE SITE(S) INDICATES THAT YOU ACCEPT THESE TERMS OF USE.</p>
    <p align="justify">&nbsp;2.4&nbsp;All Site Content and all materials and content contained within the Site(s), including but not limited to the text, graphics, logos, button icons, images, audio clips, video clips, articles, posts and data compilations appearing on the Site(s), are owned by us, or used by us under authorization, and are protected by U.S. and foreign trademark and copyright laws. No portion of the materials or content on these pages may be reprinted or republished in any form without our express written permission, except as expressly permitted herein.</p>
    <p align="justify">&nbsp;2.5&nbsp;These Terms of Use will govern any upgrades or updates provided by us that replace and/or supplement the original Site(s).</p>
    <p align="justify"><strong>&nbsp;3.&nbsp;<u>Infringement Notice.</u></strong></p>
    <p align="justify">&nbsp;3.1&nbsp;We respect the intellectual property rights of others and require that our users do the same. If you believe your work has been copied in a manner that constitutes copyright infringement, or you believe your rights are otherwise infringed or violated by anything on the Site(s), please notify us by sending an email at the following address:  <a href="mailto:dmca@rewardthefan.com">dmca@rewardthefan.com</a>.</p>
    <p align="justify">&nbsp;3.2&nbsp;In order for us to more effectively assist you, the notification must include all of the following:</p>
    <p align="justify">&nbsp;&nbsp;a.&nbsp;A physical or electronic signature of the owner of the right claimed to be infringed or the person authorized to act on the owner's behalf; </p>
    <p align="justify">&nbsp;&nbsp;b.&nbsp;A description of the copyrighted work or other right you claim has been infringed or violated;</p>
    <p align="justify">&nbsp;&nbsp;c.&nbsp;Information reasonably sufficient to locate the material in question on the Site(s);</p>
    <p align="justify">&nbsp;&nbsp;d.&nbsp;Your name, address, telephone number, e-mail address and all other information reasonably sufficient to permit us to contact you;</p>
    <p align="justify">&nbsp;&nbsp;e.&nbsp;A statement by you that you have a good faith belief that the disputed use is not authorized by the rightful owner, its agent or the law; and </p>
    <p align="justify">&nbsp;&nbsp;f.&nbsp;A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the owner of the right claimed to be infringed or violated or are authorized to act on behalf of the owner. </p>
    <p align="justify">&nbsp;3.3&nbsp;Upon notification of potentially infringing material, it is our policy to: (i) remove or disable access to the potentially infringing material; and (ii) notify the user of the potentially infringing material that we have removed or disabled access to the material. We reserve the right but not the obligation to terminate a User's access to the Site(s) upon notice of such infringement(s).</p>
    <p align="justify">&nbsp;3.4&nbsp;If the potentially infringing user believes that he/she has the right to post and use such material, such user may send a "counter-notice" to  <a href="mailto:dmca@rewardthefan.com">dmca@rewardthefan.com</a> containing the following information: </p>
    <p align="justify">&nbsp;&nbsp;a.&nbsp;A physical or electronic signature of the potentially infringing user; </p>
    <p align="justify">&nbsp;&nbsp;b.&nbsp;A description of the potentially infringing material that has been removed or access disabled;</p>
    <p align="justify">&nbsp;&nbsp;c.&nbsp;A statement that the user has a good faith belief that the material was removed or disabled as a result of a mistake or a misidentification of the material; and </p>
    <p align="justify">&nbsp;&nbsp;d.&nbsp;User's name, address, telephone number, and, if available, e-mail address and a statement that such person or entity consents to the jurisdiction of the federal court for the judicial district in which the user's address is located, or if the user's address is located outside the United States, for any judicial district in which RTF LIVE is located, and that such person or entity will accept service of process from the person who provided notification of the alleged infringement.   </p>
    <p align="justify">&nbsp;3.5&nbsp;We may send a copy of the counter-notice to the original complaining party informing that party that he/she may elect to withdraw his/her infringement notice within ten (10) business days of the sent date time stamp of our email notifying him/her of same. If such user elects to withdraw his/her infringement notice, the previously removed content may be restored to the Site(s), at our sole discretion. Save for a court order or the existence of related pending civil proceedings, we may decide at our sole discretion to restore the alleged infringing material to the Site(s) at any time. </p>
    <p align="justify">&nbsp;3.6&nbsp;For more information or to report an alleged infringement, please contact our Designated Agent at the following address: RTF LIVE, Attn: DMCA Designated Agent, 159-16 Union Turnpike Suite 212, Fresh Meadows, NY  11366 or email: <a href="mailto:dmca@rewardthefan.com">dmca@rewardthefan.com</a>.  </p>
    <p align="justify"><strong>&nbsp;4.&nbsp;<u>Errors and Inaccuracies. </u></strong></p>
    <p align="justify">&nbsp;4.1&nbsp;We strive to provide complete, accurate, up-to-date information on the Site(s). Unfortunately, despite those efforts, human or technological errors may occur. The Site(s) may contain typographical mistakes, inaccuracies, or omissions, some of which may relate to pricing and availability of products or the events we promote, and some information may not be complete or current. We reserve the right to correct any errors, inaccuracies or omissions, including after an order has been submitted, and to change or update information at any time without prior notice.</p>
    <p align="justify">&nbsp;4.2&nbsp;Force Majeure. We will not be liable to you for any delay or failure to perform any obligation or services related to the Site(s) if the delay or failure results from any cause beyond our reasonable control, including acts of God, labor disputes or other industrial disturbances, systemic electrical, telecommunications, or other utility failures, earthquake, storms or other elements of nature, blockages, embargoes, riots, acts or orders of government, acts of terrorism, or war.</p>
    <p align="justify">&nbsp;4.3&nbsp;At times, it may be necessary for us to install updates and/or maintenance to our Software and the Site(s), thereby potentially impacting your access to our Service(s). In this case, we will use commercially reasonable efforts to provide notice to you of said interruptions. </p>
    <p align="justify"><strong>&nbsp;5.&nbsp;<u>Changes to Site(s) or These Terms of Use. </u></strong></p>
    <p align="justify">&nbsp;5.1&nbsp;Other than as may be required by law, we reserve the right to modify or remove, temporarily or permanently, the Site(s) (or any part thereof) with or without notice to you. You confirm that we shall not be liable for any modification or removal of the Site(s) or any portion of it. </p>
    <p align="justify">&nbsp;5.2&nbsp;We may alter these Terms of Use from time to time, and your use of the Site(s) (or any part thereof) following such change(s) shall constitute your acceptance of such change(s). It is your responsibility to review these Terms of Use regularly. If you do not agree to any change to the Terms of Use, you must immediately stop using the Site(s).</p>
    <p align="justify">&nbsp;5.3&nbsp;The Site(s) is subject to constant change. You will not be eligible for any compensation in the case you cannot use any part of the Site(s), or because of a failure, suspension or withdrawal of all or part of the Site(s) and/or Service(s).</p>
    <p align="justify"><strong>&nbsp;6.&nbsp;<u>Third Party Content. </u></strong></p>
    <p align="justify">The Site(s) may contain links to other websites and other content, including without limitation graphics and photographs, that are owned and/or operated by third parties ("Third Party Content"). We are not responsible for the availability of any Third Party Content. Unless expressly noted, we do not endorse any third parties or Third Party Content. You acknowledge that we are not liable, directly or indirectly, for any claims arising out of Third Party Content, including without limitation defamation, misrepresentation, false advertising, economic loss, and offense.</p>
    <p align="justify"><strong>&nbsp;7.&nbsp;<u>Account Registration </u></strong></p>
    <p align="justify">&nbsp;7.1&nbsp;In order to list or sell goods and services through the Site(s) you must register an account with RTF LIVE. To register, you must be at least eighteen (18) years old, or thirteen (13) old with parental consent, to enter into and form a legally binding contract. In addition, you must be in good standing and not an individual that has been previously barred from receiving RTF LIVE's Service(s) under the laws and statutes of the United States or other applicable jurisdiction, or in our sole discretion. We reserve the right to deny or terminate registration or membership for the Site(s) for any reason in our sole discretion. </p>

    <p align="justify">&nbsp;7.2&nbsp;When you set up an account, you are the sole authorized user of your account. You shall be responsible for maintaining the secrecy and confidentiality of your password and for all activities that transpire on or within your account. It is your responsibility for any act or omission of any user(s) that access your account information that, if undertaken by you, would be deemed a violation of these Terms of Use. It shall be your responsibility to notify us immediately if you notice any unauthorized access or use of your account or password or any other breach of security. We shall not be held liable for any loss and/or damage arising from any failure to comply with any portion or condition of these terms.</p>
    <p align="justify">&nbsp;7.3&nbsp;When you register to use and access to the Site(s) and Service(s), you must provide accurate and complete information and keep your account information updated. If you provide information that is not current or information that is incomplete or inaccurate, or if we have reasonable grounds to suspect the information you provided was not current, accurate or complete, we may deny you access to the Site(s) and/or Services(s), disqualify you, cancel the purchase or sale of goods or services and/or terminate your account, at our sole discretion. </p>
    <p align="justify">&nbsp;7.4&nbsp;You will be asked to select a username when registering your account. You acknowledge that you will not select or use a username with the intent to impersonate a third party or use a username subject to any rights of a person without appropriate authorization. If you register your account with a username that we, at our sole discretion, deem to be inappropriate, obscene, vulgar or offensive, we reserve the right to revoke your access to the Site(s).</p>

    <p align="justify">&nbsp;7.5&nbsp;You are prohibited from ever using a third party's registration or account information without first obtaining permission from said third party, and you must notify us immediately of any change in your eligibility to use the Site(s), any breach of security, or any unauthorized use of your account. You may only create one account. For clarity, users may not share ownership in accounts. If we determine that you have opened, maintained, used or controlled more than one account, in addition to any other rights we may have, we reserve the right to suspend or terminate any or all of your accounts and terminate, withhold or revoke the awarding of any prizes and/or refund any goods or services sold or purchased.</p>
    <p align="justify">&nbsp;7.6&nbsp;When you register, we may collect information such as your name, e-mail address, and phone number. You can edit your account information, except your user ID, at any time. Once you register on the Site(s) and sign into our Services, you are no longer anonymous to us. By registering for RTF LIVE, you agree to receive automated promotional text messages and WhatsApp messages from or on behalf of RTF LIVE. You are not required to provide this consent as a condition of purchasing any property, goods, or services. Standard messaging rates may apply.</p>
    <p align="justify">&nbsp;7.7&nbsp;As a member of the Site(s), you may cancel or terminate your account, associated email address and/or access to our Services by submitting a cancellation or termination request to <a href="mailto:info@rewardthefan.com">info@rewardthefan.com</a>. You agree that RTF LIVE may, without any prior written notice, immediately suspend, terminate, discontinue and/or limit your account, any email associated with your account, and access to any of our Services.</p>
    <p align="justify"><strong>&nbsp;8.&nbsp;<u>Discount Codes, Reward Point Transactions and Other Prizes.  </u></strong></p>
    <p align="justify">&nbsp;8.1&nbsp;Registered Users of the Site(s) may have a chance to win Discount Codes &amp; Reward Points by playing the RTF LIVE App Trivia Game. Registered Users may redeem said Discount Codes &amp; Reward Points for goods and services on the RTF LIVE Marketplace. We do not own the goods or services available on our Site(s).  </p>
    <p align="justify">&nbsp;8.2&nbsp;<strong>Delivery of Goods and Services.</strong>  In most cases, the goods and services will be delivered promptly upon redemption of Discount Codes and Reward Points, either via mail or e-mail. In any case that the goods and services are not available for delivery at the time of the Discount Code or Reward Point redemption transaction, RTF LIVE will email the Registered User notifying him/her when his/her goods and services are available. In some cases, the goods and services may have a delayed delivery. </p>
    <p align="justify">&nbsp;8.3&nbsp;<u><strong>ALL TRANSACTIONS ARE FINAL.</strong></u>. THERE ARE NO REFUNDS, EXCHANGES, OR CANCELLATIONS ON ANY TRANSACTION ONCE IT IS SUBMITTED TO US. PLEASE REDEEM YOUR DISCOUNT CODES AND REWARD POINTS FOR THE GOODS AND SERVICES <u><strong>ONLY</strong></u> AFTER YOU ARE CERTAIN YOU WANT THEM.</p>
    <p align="justify">&nbsp;8.4&nbsp;You acknowledge that if or when pricing errors occur, RTF LIVE will not be liable to you for this error.</p>

    <p align="justify">&nbsp;8.5&nbsp;You acknowledge that we reserve the right to change the method of delivery for the goods and services you purchased and or redeemed without notice, at no additional cost to you.</p>
    <p align="justify">&nbsp;8.6&nbsp;Delivery dates and times are always subject to change. It is your responsibility to check for any possible changes on the status of your delivery. You agree that we are not responsible for changes to the date or time of the delivery and that refunds will not be issued due to delivery delays.</p>

    <p align="justify">&nbsp;8.7&nbsp;Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to provide goods and services to you in return for Reward Points. We reserve the right at any time after receipt of your order to accept or decline your order for any reason or to supply less than the quantity you ordered of any item.</p>    
    <p align="justify">&nbsp;8.8&nbsp;Registered Users of the Site(s) may also have a chance to play in-game contests when playing the RTF LIVE App Shoppable Trivia Game. Any such in-game contests and corresponding prizes will be announced during the RTF LIVE App Shoppable Trivia Game and all prizes will be awarded in connection with these Terms of Use. </p>

    <p align="justify"><strong>&nbsp;9.&nbsp;<u>Returns</u></strong></p>
    <p align="justify">&nbsp;9.1&nbsp;In the event that we cancel your order, we will reinstate the full amount of Reward Points redeemed for orders we cancel. We will determine, at our sole discretion, if and when an order is canceled "canceled" for the purpose of issuing refunds. </p>
    <p align="justify">&nbsp;9.2&nbsp;In order to qualify for and receive a return of Reward Points, users who redeemed goods or services must return the physical goods purchased, if any, to RTF LIVE by following the instructions and prompts contained in the notice email. In any event, returned goods must be postmarked no later than ten (10) days after the sent date timestamp of RTF LIVE's email notifying user of his/her right to a refund. In the case that no physical goods were shipped, users seeking a refund must follow the instructions and prompts contained in the notice email.</p>
    <p align="justify"><strong>&nbsp;10.&nbsp;<u>Lost or Stolen Goods.</u></strong></p>
    <p align="justify">We are not responsible for lost or stolen goods and you will not be eligible for a refund in the case the goods you purchased or redeemed are lost or stolen. </p>
    <p align="justify"><strong>&nbsp;11.&nbsp;<u>User Generated Content.  </u></strong></p>
    <p align="justify">&nbsp;11.1&nbsp;The Site(s) contains or may contain various interactive portions, such as a user forum, message board or other types of interactive features that allow users to post content on our Site(s) ("Online Services"). We have no obligation to offer and/or actively monitor the Online Services, but we reserve the right to do so. We are not responsible for, nor do we vouch for the accuracy of, the content of any user comments or other content that may be posted or uploaded by a user. User comments and other content posted or uploaded by a user ("User Content") express the views and opinions of the user and do not necessarily reflect our views or opinions. We reserve the right, in our sole discretion, to edit, delete, or refuse to post User Content, for any reason whatsoever. </p>
    <p align="justify">&nbsp;11.2&nbsp;If you believe that any User Content is inaccurate or objectionable, you may contact us by sending an email to  <a href="mailto:info@rewardthefan.com">info@rewardthefan.com</a>. and include the words "OBJECTIONABLE CONTENT" in the subject. Please provide us with detailed information about the nature and location of the alleged objectionable material so that we may easily locate and investigate the same. </p>
    <p align="justify">&nbsp;11.3&nbsp;By using the Site(s), you agree that:</p>
    <p align="justify">&nbsp;&nbsp;a.&nbsp;You will not upload, post, email or otherwise transmit any material or other content that: (i) is defamatory, libelous, disruptive, threatening, invasive of a person's privacy, harmful, abusive, harassing, obscene, hateful, or racially, ethnically or otherwise objectionable; or that otherwise violates any law; (ii) contains software viruses or any other computer codes, files or programs designed to interrupt, destroy, or limit the functionality of any computer software or hardware or telecommunications equipment; (iii) infringes any person or entity's intellectual property rights (including but not limited to, patent, trademark, trade secret, copyright or other intellectual property right). </p>
    <p align="justify">&nbsp;&nbsp;b.&nbsp;You will not impersonate any person or entity or otherwise misrepresent your affiliation with a person or entity.</p>
    <p align="justify">&nbsp;&nbsp;c.&nbsp;You will not repeatedly post the same or similar message ("flooding") or post excessively large or inappropriate images or content. </p>
    <p align="justify">&nbsp;&nbsp;d.&nbsp;You will not distribute or publish unsolicited promotions, advertising or solicitations for funds, goods or services, including but not limited to, junk mail, spam and chain letters.</p>
    <p align="justify">&nbsp;11.4&nbsp;We do not guarantee that any User Content will be displayed on the Site(s), and we reserve the right, but do not have any obligation to: (i) remove, edit or modify or otherwise manipulate any User Content in our sole discretion, at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such User Content, or if we are concerned that you may have violated these Terms of Use), or for no reason at all; and (ii) to remove or block any User Content from the Site(s).</p>

    <p align="justify">&nbsp;11.5&nbsp;User Content may become public information, in whole or in part. You should be very careful about posting personally identifiable information such as your name, address, telephone number or email address. If you post personal information online, you may receive unsolicited messages from other users in return.</p>

    <p align="justify">&nbsp;11.6&nbsp;You are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password, regardless of whether such use is authorized by you or not.</p>
    <p align="justify">&nbsp;11.7&nbsp;If you submit any User Content, you grant to us, and any of our successors, licensees, assigns, and affiliates, a royalty-free, worldwide, perpetual, irrevocable, non-exclusive and fully sub-licensable right and license to use, reproduce, modify, edit, adapt, publish, translate, create derivative works from, distribute, perform and display the User Content, and in any other media, now known or hereafter devised. We may use your User Content for any purposes, including without limitation, to promote the Site(s) and RTF LIVE more generally. </p>
    <p align="justify">&nbsp;11.8&nbsp;You represent and warrant that you have all rights to grant such licenses to us without infringement or violation of any third-party rights, including without limitation, any privacy rights, publicity rights, copyrights, trademarks, contract rights, or any other intellectual property or proprietary rights. </p>
    <p align="justify">&nbsp;11.9&nbsp;If you choose to communicate or meet with other users of the Site(s), you are doing so at your own risk. We do not, and have no obligation to, verify the identity of or otherwise screen our users for any reason. You acknowledge that there are risks, including the risk of physical harm, when dealing with strangers or people acting under false pretenses. You assume all risks associated with dealing with other users with whom you may come in contact through the Site(s). </p>
    <p align="justify">&nbsp;11.10&nbsp;The Site(s) is meant for users eighteen (18) years old and over, or thirteen (13) years old with parental consent. We will not knowingly allow any user less than eighteen (18) years of age, or thirteen (13) with parental consent, to submit any User Content to our Site(s) </p>

    <p align="justify"><strong>&nbsp;12.&nbsp;<u>Comments, Feedbacks and Suggestions </u></strong></p>
    <p align="justify">You acknowledge that any comments, feedback, suggestions, ideas, pictures, video etc. disclosed, submitted or offered to us (collectively, "Feedback"), shall remain our exclusive property that we may use in any medium and for any purpose without obtaining your specific consent. You further acknowledge that we are not under any obligation to maintain your name or Feedback in confidence or to pay to you any compensation for any Feedback you may submit. We are not obligated to respond to any of your Feedback but may choose to do so at our sole discretion. You agree that you will be solely responsible for the content of any Feedback you create and submit.</p>

    <p align="justify"><strong>&nbsp;13.&nbsp;<u>General Conditions   </u></strong></p>
    <p align="justify">&nbsp;13.2&nbsp;You may not create, develop, license, install, use, or deploy any third-party software or services to circumvent, enable, modify or provide access, permissions or rights to work around any technical limitations in the Site(s). You may not copy (except as expressly permitted by these Terms of Use) or publish the Site(s) or contents thereof for others to copy, decompile, reverse engineer, disassemble, attempt to derive the source code of, or modify, or create derivative works of the Site(s), or any updates, or part thereof (except as and only to the extent any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open source components included with the Site(s), if any). Any attempt to do so is a violation of our rights. If you breach this restriction, you may be subject to prosecution and damages. You may not use the Site(s) in any manner not specifically authorized hereunder or in any way that is against any applicable laws or regulations.</p>
    <p align="justify">&nbsp;13.3&nbsp;We reserve the right to suspend or cease providing access to the Site(s) and the Service(s) offered therein, with or without notice, and we shall have no liability or responsibility to you if we do so.</p>
    <p align="justify"><strong>&nbsp;14.&nbsp;<u>Disclaimers  </u></strong></p>
    <p align="justify">&nbsp;14.1&nbsp;WE MAKE NO WARRANTIES, WHETHER EXPRESS OR IMPLIED IN RELATION TO THE ACCURACY OF ANY INFORMATION ON THE SITE(S). THE SITE(S) IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY REPRESENTATION. WE MAKE NO WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, IN RELATION TO THE SITE(S), INCLUDING BUT NOT LIMITED TO, IMPLIED WARRANTIES OF SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, COMPATIBILITY, SECURITY, ACCURACY, CONDITION OR COMPLETENESS, OR ANY IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OR TRADE. </p>
    <p align="justify">&nbsp;14.2&nbsp;WE MAKE NO WARRANTY THAT THE SITE(S) WILL MEET YOUR REQUIREMENTS OR WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SITE(S) OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR BUGS OR ARE FULLY FUNCTIONAL, ACCURATE, OR RELIABLE.</p>
    <p align="justify">&nbsp;14.3&nbsp;AS SET FORTH IN THE SITE(S) PRIVACY POLICY, YOU ACKNOWLEDGE THAT WE CANNOT GUARANTEE, AND THEREFORE SHALL NOT BE IN ANY WAY RESPONSIBLE FOR, THE SECURITY OR PRIVACY OF THE SITE(S) AND ANY INFORMATION PROVIDED TO OR TAKEN FROM THE SITE(S) BY YOU.</p>
    <p align="justify"><strong>&nbsp;15.&nbsp;<u>Limitations on Liability </u></strong></p>
    <p align="justify">IN NO EVENT WILL RTF LIVE, OR ITS OFFICERSM MEMBERS, DIRECTORS, EMPLOYEES, PARENTS, AFFILIATES, SUCCESSORS OR ASSIGNS (THE "RELEASED PARTIES"), BE LIABLE TO ANY PARTY FOR ANY ECONOMIC LOSSES (INCLUDING WITHOUT LIMITATION ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES, LOSS OF REVENUES, PROFITS, CONTRACTS, BUSINESS OR ANTICIPATED SAVINGS) OR ANY LOSS OF GOODWILL OR REPUTATION, OR ANY LOSS OR CORRUPTION OF DATA, OR ANY SPECIAL OR INDIRECT OR CONSEQUENTIAL LOSSES ARISING OUT OF YOUR USE OF THE SITE(S); IN ANY CASE WHETHER OR NOT SUCH LOSSES WERE WITHIN THE CONTEMPLATION OF US AT THE DATE ON WHICH THE EVENT GIVING RISE TO THE LOSS OCCURRED. THIS INCLUDES BUT IS NOT LIMITED TO ANY INJURY CAUSED BY ANY VIRUSES, BUGS, HUMAN ACTION OR INACTION OR ANY COMPUTER SYSTEM, PHONE LINE, HARDWARE, SOFTWARE, OR PROGRAM MALFUNCTIONS, OR ANY OTHER ERRORS, FAILURES OR DELAYS IN COMPUTER TRANSMISSIONS OR NETWORK CONNECTIONS, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY</p>
    <p align="justify"><strong>&nbsp;16.&nbsp;<u>Indemnification  </u></strong></p>
    <p align="justify">BY USING THE SITE(S), YOU AGREE TO INDEMNIFY, DEFEND, AND HOLD HARMLESS THE RELEASED PARTIES AGAINST ALL CLAIMS, LIABILITY, DAMAGES, LOSSES, COSTS AND EXPENSES, INCLUDING LEGAL FEES, SUFFERED BY THE RELEASED PARTIES AND ARISING OUT OF ANY USER CONTENT YOU POST TO THE SITE(S) AND ANY BREACH OF YOUR REPRESENTATIONS AND WARRANTIES OR THESE TERMS OF USE BY YOU OR ANY OTHER LIABILITIES ARISING OUT OF YOUR USE OF THE SITE(S), OR THE USE BY ANY OTHER PERSON ACCESSING THE SITE(S) USING YOUR COMPUTER OR INTERNET ACCESS ACCOUNT. WE RESERVE THE RIGHT TO CONTROL THE DEFENSE OF ANY IDEMNIFIED MATTERS THROUGH COUNSEL OF OUR OWN CHOOSING.</p>
    <p align="justify"><strong>&nbsp;17.&nbsp;<u>Investigations of Violations of These Terms </u></strong></p>
    <p align="justify">We may investigate any reported violation of these Terms of Use and take any action that we deem appropriate. Such action may include, but is not limited to, issuing warnings, removing posted content and reporting any activity that we suspect violates any law or regulation to appropriate law enforcement officials, regulators, or other third parties.</p>
    <p align="justify"><strong>&nbsp;18.&nbsp;<u>State Specific Notices   </u></strong></p>
    <p align="justify">&nbsp;18.1&nbsp;<u>Notice for California Users</u>. Under California Civil Code Section 1789.3, California Website users are entitled to know that they may file grievances and complaints with: the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs, in writing at 1625 North Market Blvd., Suite N 112, Sacramento CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210 or by email  at<a href="mailto:dca@dca.ca.gov">dca@dca.ca.gov</a>.</p>
    <p align="justify">&nbsp;18.2&nbsp;<u>Notice For New Jersey Users.</u> Any disclaimer, limitation of liability, indemnification or damages provisions contained herein shall apply to New Jersey residents or New Jersey transactions only to the extent permitted by New Jersey law or New Jersey public policy.</p>
    <p align="justify"><strong>&nbsp;19.&nbsp;<u>Choice of Law, Binding Arbitration Clause </u></strong></p>
    <p align="justify">&nbsp;19.1&nbsp;These Terms will be interpreted in accordance with the laws of the State of New York and the United States of America, without regard to its conflict-of-law provisions.</p>
    <p align="justify">&nbsp;19.2&nbsp;By visiting the Site(s), you agree that, except as otherwise specified herein, the laws of the State of New York without regard to principles of conflict of laws, will govern any dispute of any sort that might arise between us or any of our affiliates regarding your visit and use of the Site(s) and Services. </p>
    <p align="justify">&nbsp;19.3&nbsp;We and you agree that in the event of any dispute, the party wishing to address the dispute must contact the other party in writing, including by e-mail, and advise the other party of the dispute in reasonable detail as well as informing the other party of the remedy being sought. We may send you notices via the email address or physical address you provide to us, and all notices to us shall be sent to the following email address <a href="mailto:info@rewardthefan.com">info@rewardthefan.com</a>. and include the words "DISPUTE NOTICE" in the subject. The parties shall then make a good faith effort to resolve the dispute before resorting to more formal means of resolution. In the event that the dispute is not resolved through this procedure, the party raising the dispute may proceed to mandatory arbitration as set forth below.</p>
    <p align="justify">&nbsp;19.4&nbsp;ANY AND ALL DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING ARBITRATION. YOU HEREBY AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under these Terms of Use, except for matters that may be taken to small claims court. Your rights will be determined by a neutral arbitrator, NOT a judge or jury. You agree that any dispute arising out of or relating to these Terms of Use, including with respect to the interpretation of any provision of these Terms of Use or other agreements between you and us, or concerning the performance or obligations of you and us, shall be resolved by mandatory and binding arbitration submitted to JAMS in accordance with its Commercial Arbitration Rules at the request of either us or you pursuant to the following conditions:</p>
    <p align="justify">&nbsp;&nbsp;a.&nbsp;Place of Arbitration Hearings. Unless you elect to conduct the arbitration by telephone or written submission, an in-person arbitration hearing will conducted at a JAMS facility in your area or at a JAMS facility in New York, New York.</p>
    <p align="justify">&nbsp;&nbsp;b.&nbsp;Selection of Arbitrator shall be made pursuant to JAMS' Streamlined Arbitration Rules &amp; Procedures or JAMS' Comprehensive Arbitration Rules &amp; Procedures, depending on the amount of the claim as specified herein.</p>
    <p align="justify">&nbsp;&nbsp;c.&nbsp;Conduct of Arbitration. The arbitration shall be conducted by a single neutral arbitrator under JAMS' Streamlined Arbitration Rules &amp; Procedures. For claims exceeding $5,000.00, the arbitration shall be conducted under JAMS' Comprehensive Arbitration Rules &amp; Procedures Subject to the applicable JAMS procedure, the arbitrator shall allow reasonable discovery in the forms permitted by the Federal Rules of Civil Procedure, to the extent consistent with the purpose of the arbitration. The arbitrator(s) shall have no power or authority to amend or disregard any provision of this section or any other provision of these Terms of Use, except as necessary to comply with JAMS' Policy on Consumer Arbitrations Pursuant to Pre-Dispute Clauses Minimum Standards of Procedural Fairness. The arbitration hearing shall be commenced promptly and conducted expeditiously. If more than one day is necessary, the arbitration hearing shall be conducted on consecutive days unless otherwise agreed in writing by the parties. </p>
    <p align="justify">&nbsp;&nbsp;d.&nbsp;Findings and Conclusions. The arbitrator(s) shall, after reaching judgment and award, prepare and distribute to the parties written findings of fact and conclusions of law relevant to such judgment and award and containing an opinion setting forth the reasons for the giving or denial of any award. The award of the arbitrator(s) shall be final and binding on the parties, and judgment thereon may be entered in a court of competent jurisdiction.</p>
    <p align="justify">&nbsp;&nbsp;e.&nbsp;Costs and Fees. You will be subject to a filing fee, set by JAMS, to initiate the arbitration. To the extent permitted by JAMS procedures, each party shall bear its own costs and expenses and an equal share of the arbitrators' and administrative fees of arbitration, and we will remain responsible for its share of costs, expenses and fees plus any costs, expenses and fees required under JAMS procedures.</p>
    <p align="justify">&nbsp;&nbsp;f.&nbsp;Litigation. The Federal Arbitration Act and federal arbitration law apply to these Terms. Either party also may, without waiving any remedy under these Terms of Use, seek from any court having jurisdiction any interim or provisional relief that is necessary to protect the rights or property of that party, pending the establishment of the arbitral tribunal (or pending the arbitral tribunal's determination of the merits of the controversy).</p>
    <p align="justify">&nbsp;19.5&nbsp;Notwithstanding the arbitration clause herein, the parties also agree that RTF LIVE may bring suit in a court located in New York, New York, to enjoin infringement or other misuse of our intellectual property rights.</p>
    <p align="justify"><strong>&nbsp;20.&nbsp;<u>Class-Action Waiver </u></strong></p>
    
    <p align="justify"><strong>&nbsp;21.&nbsp;<u>Miscellaneous   </u></strong></p>
    <p align="justify">Any arbitration, claim or other proceedings by or between you and us shall be conducted on an individual basis and not in any class action, mass action, or on a consolidated or representative basis. You further agree that the arbitrator shall have no authority to award class-wide relief or to combine or aggregate similar claims or unrelated transactions. You acknowledge and agree that this agreement specifically prohibits you from commencing arbitration proceedings as a representative of others. If for any reason a claim proceeds in court rather than in arbitration, each party waives any right to a jury trial. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator.<p align="justify">Any arbitration, claim or other proceedings by or between you and us shall be conducted on an individual basis and not in any class action, mass action, or on a consolidated or representative basis. You further agree that the arbitrator shall have no authority to award class-wide relief or to combine or aggregate similar claims or unrelated transactions. You acknowledge and agree that this agreement specifically prohibits you from commencing arbitration proceedings as a representative of others. If for any reason a claim proceeds in court rather than in arbitration, each party waives any right to a jury trial. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator.</p></p>
    <p align="justify">&nbsp;21.1&nbsp;If any part of these Terms of Use shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed to be severable from these Terms of Use and shall not affect the validity and enforceability of any of the remaining provisions of the Terms of Use.</p>
    <p align="justify">&nbsp;21.2&nbsp;These Terms as well as our  <a href="http://www.rewardthefan.com/PrivacyPolicy">Privacy Policy</a>, the RTF LIVE  <a href="http://www.rewardthefan.com/Rules">Official Rules</a>, and any other terms or agreements that may be posted on the Site(s) (as may be amended from time to time) ("Site(s) Agreements") contain the entire agreement between you and us relating to the Site(s) and your use of the Site(s), and supersede any previous agreements, arrangements, undertakings or proposals, written or oral, between you and us in relation to such matters. No oral explanation or oral information shall alter the interpretation of these Site(s) Agreements. You confirm that, in agreeing to accept these Site(s) Agreements, you have not relied on any representation except insofar as the same has expressly been made a representation in these Site(s) Agreements, and you agree that you shall have no remedy in respect of any representation which has not become a term of these Site(s) Agreements. These Site(s) Agreements will be exclusively governed by and construed in accordance with the laws of the State of New York and, subject to the Arbitration Clause contained herein, the courts located in the City of New York, New York will have exclusive jurisdiction in any dispute, except that we have the right, at our sole discretion, to commence and pursue proceedings in alternative jurisdictions (again subject to the arbitration clause contained herein).</p>
    <p align="justify">&nbsp;21.3&nbsp;To understand our privacy practices, please review our <a href="http://www.rewardthefan.com/PrivacyPolicy">Privacy Policy</a> which governs your visit to this Site, and which is hereby incorporated by reference into these terms.</p>
    <p align="justify">&nbsp;21.4&nbsp;You shall not transfer, assign, sublicense nor pledge in any manner whatsoever, any of your rights or obligations under these Terms of Use. We may transfer, assign, sublicense or pledge in any manner whatsoever, any of our rights and obligations under these Terms of Use to a subsidiary, affiliate, or successor thereof or to any third party whatsoever, without notifying you or receiving your consent.</p>
    <p align="justify">&nbsp;21.5&nbsp;Our failure to exercise or enforce any right or provision of these Terms of Use shall not constitute a waiver of such right or provision. No independent contractor, partnership, joint venture or employer-employee relationship is intended or created. No action, regardless of form, which arises from or is related in any way whatsoever to these Terms of Use, may be commenced by you more than twelve (12) months after such cause of action accrues. All notices and other communications under the Terms must be in writing and will be deemed to have been duly given when actually received. You may provide notices to us via (i) email to <a href="mailto:info@rewardthefan.com">info@rewardthefan.com</a>, or (ii) by writing to us at RTF LIVE, 159-16 Union Turnpike Suite 212, Fresh Meadows, NY  11366.</p>
    <p align="justify">If you have any questions regarding these Terms of Use or the Website, App or Services, please contact us at <a href="mailto:info@rewardthefan.com">info@rewardthefan.com</a>.</p>
    <p align="justify"><strong>DATE LAST MODIFIED: Dec 15, 2020</strong></p>



    </div>
    </div>

</div>

</div>
<Footer/>
</>
)
}
