import React,{useEffect} from 'react';
import Header from "../../component/Header"
import Footer from "../../component/Footer";


export default function DCMA(props) {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  });

    return(
    <>
<Header withbg={true}  {...props} />
<div className="contactpage page pb0">
  
<div className=" imgbox  platformcard paddrem1 innpage">
  <h2>Privacy Policy</h2>
  <div className="container_custom container-fluid ">
            <div class="media-body media-body-2 ">
         

            <p align="justify">RTF LIVE   and its subsidiaries and affiliates (individually or collectively “we/our/us” or “RTF LIVE”) respect your privacy and are committed to protecting it through compliance with this policy. Our privacy policy, is designed to explain the information we collect and how we use it to provide our services and give Users a better experience (“Privacy Policy”). This Privacy Policy is part of, and incorporated into, our Terms of Use.  </p>
            <p align="justify">This Privacy Policy describes the type of information we may collect from you and/or that you may provide us when you visit and/or use any Site(s), mobile site(s) and/or app(s) provided by us, including without limitation <a href="https://www.rtflive.com/">www.rtflive.com</a> and the RTF LIVE mobile application (individually or collectively, “Site(s)”). “You/your/user(s)” means you as a user of our Site(s), including any information, tools and services available from the Site(s), conditioned upon your acceptance of all the terms, conditions, policies and notices stated here, which you accept by continuing to utilize the Site(s).  </p>
            <p align="justify">By accessing and using the Site(s), you consent to our collection, storage, use and disclosure of your personal information and other information as described in this Privacy Policy. </p>
            <p align="justify"><strong><u>Guide to Contents</u></strong><br/></p>
            <ol><li>Scope</li><li>Types of Information We Collect</li><li>How We Use Your Information</li><li>How We Share and Disclose Information with Third Parties</li><li>Non-Personally Identifiable Information</li><li>Your Choices/Opt-Out</li><li>Your Security</li><li>Links to Other Site(s)</li><li>Children</li><li>Changes to Our Privacy Policy</li><li>California Privacy Rights</li><li>Disclosure for Legal Purposes</li><li>Non-Confidential Information</li><li>Assignment</li><li>Disputes</li><li>Class Action Waiver</li><li>Contact Us</li></ol>
            <p align="justify"><strong>&nbsp;1.&nbsp;<u>Scope  </u></strong></p>
            <p align="justify">&nbsp;1.1&nbsp;We value our users and respect your privacy. This Privacy Policy describes the Personal Information (as defined below) we collect about you online on the Site(s), why we collect it, how we use it, and when we share it with third parties. This Privacy Policy also describes the choices you can make about how we collect and use certain of that information.</p>
            <p align="justify">&nbsp;1.2&nbsp;The Privacy Policy does not apply to information collected by us offline or through any other means, including any third party or any application or content (including advertising) that may link to or be accessible from or on the Websites. </p>
            <p align="justify">&nbsp;1.3&nbsp;Although many areas of the Site(s) do not require registration and may be accessed by you without having to disclose any personal information, we or our service providers and/or third party advertisers may ask you for certain kinds of personal information, including but not limited to your name, email address, mailing address, telephone number, age, credit/debit card information, user name and password, demographic information and other information that might identify you as an individual (“Personal Information”). The Personal Information we collect about you may also be combined or supplemented with information from other sources. Any Personal Information used in any manner will be used consistent with this Privacy Policy. </p>
            <p align="justify">&nbsp;1.4&nbsp;By accessing the Site(s), you acknowledge this Privacy Policy and agree to be bound by the terms hereof and the Terms of Use set forth on the Site(s). If there is anything you do not understand please email any inquiry to. <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a>. <strong>If at any time you do not agree to this Privacy Policy, please do not use the Site(s)</strong>. </p>
            <p align="justify">&nbsp;1.5&nbsp;We reserve the right to change or update this Privacy Policy by posting such changes or updates to the Site(s). Amendments to this Privacy Policy will be posted at <a href="https://www.rtflive.com//terms">www.rtflive.com/terms</a> and will be effective when posted. It is your responsibility to review any such changes or updates and to check the Site(s) regularly to be sure you understand all terms and conditions, agreements and policies of the Site(s) and are in compliance with same. The “Last Modified” date indicates if and as of when changes have been made to this Privacy Policy. Your continued use of the Site(s) following the posting of any amendment, modification or change shall constitute your acceptance thereof. </p>
            <p align="justify"><strong>&nbsp;2.&nbsp;<u>Types of Information We Collect.</u></strong></p>
            <p align="justify">&nbsp;2.1&nbsp;We collect both "Personal Information" and "Anonymous Information" about our users. Personal Information is information that can be used to contact or identify you, such as your full name, email address, phone number, street address, as well as information that is linked to such information. Anonymous Information is information that cannot be used to contact or identify you, and is not linked to information that can be used to do so. It includes passively collected information about your activities on the Site(s), including, without limitation, usage data.  </p>
            <p align="justify">&nbsp;2.2&nbsp;Users can access and browse a majority of the Site(s), including downloading the RTF LIVE mobile application (the “App”) without disclosing any Personal Information. However, akin to most website and mobile app providers, we passively collect certain information from your devices, such as your IP address, browser information, unique device identifier (“UDID”) and/or your mobile operating system. </p>
            <p align="justify">&nbsp;2.3&nbsp;We may collect information that you provide directly to us. You may provide different types of Personal Information to us if and when you engage in certain activities that may be provided on the Site(s), such as creating an account, playing the RTF LIVE App Trivia Game, ordering a product or service, requesting information about career opportunities, submitting, posting or accessing various content or features, responding to and submitting a form(s), participating in our blogs, podcasts or forums, entering a sweepstakes, contest, promotion or other special initiative, signing up for a special offer, completing a survey, sending feedback, requesting or submitting information, or directly contacting us. It is optional for you to engage in such activity; however, if you choose to do so, we may require that you provide us certain Personal Information. Depending upon the activity, some of the information we ask you to provide is required and some is voluntary. If you do not provide required information for a particular activity, you may not be permitted to engage in that activity.</p>
            <p align="justify">&nbsp;2.4&nbsp;We may also collect certain information automatically, including through use of cookies, web beacons and other technologies. This information may include the following: your browser and mobile device type, operating system and name of your Internet service provider; web pages you visit on the Site(s); IP address, browser type, profile information, geo-location information; information about your interactions with email messages, such as whether the messages were opened and the links clicked in those emails; and standard server log information.</p>
            <p align="justify">&nbsp;2.5&nbsp;We collect email lists and information related to meeting requests and marketing services. When you use the Site(s), you may be given the option to subscribe to or to be added to our subscription or email list, to schedule a personal call/meeting and to request certain resource materials. Whether or not you select this/these option(s), your Personal Information may be shared with third parties consistent with this Privacy Policy. You may opt-out or unsubscribe from these email list or call/meeting requests at any time.</p>
            <p align="justify">&nbsp;2.6&nbsp;We collect Personal Information that you provide when you set up your account/become a registered user. You have the opportunity to create account(s) on the Site(s), which may include a shopping account with us. A shopping account may allow you to shop faster and easier, check on order status and history, post comments to the Site(s) and to use certain other features of the Site(s). Using your email and password of your choice, you may access your account online at any time to add, delete, or change information. The Personal Information provided by you is not used for any purpose other than as outlined in this Privacy Policy. If you ever use a public computer to access the Site(s) account, we strongly encourage you to log out at the conclusion of your session. By doing so, although your Personal Information may still be stored with us, it should not be accessible to anyone else from that computer.  </p>
            <p align="justify">&nbsp;2.7&nbsp;We collect Personal Information provided by registered users. In creating an account and saving it for your next visit, you authorize us to store your name, address, email address, telephone number and other Personal Information that you may provide. With the exception of email addresses, and cell phone numbers, registered users’ voluntary personal profile information, including pictures, may be displayed to other registered users in order to facilitate user interaction. Registered users’ user names are displayed to all users, although each verified user has the option of having his or her full name displayed to all users instead of his or her user name. We therefore encourage you to choose a user name that is not your actual name. Under no circumstances are email addresses, or cell phone numbers directly revealed to other users or disclosed to third parties other than as set forth in this Privacy Policy.</p>
            <p align="justify">&nbsp;2.8&nbsp;Only some payment processing information is collected by us. We may also use a third party(ies) for payment processing. We do not want you to send us your credit card or bank account information by email or other means except where requested as part of the checkout process. Please review the terms of use and privacy policies of the third party payment processor prior to providing Personal Information to them. </p>
            <p align="justify">&nbsp;2.9&nbsp;If you access the Services through a desktop or mobile device, we may access, collect, monitor and/or remotely store geo-location data. </p>
            <p align="justify">&nbsp;2.10&nbsp;You may also be able to register for or login to the Site(s) through certain social media accounts, such as Facebook. In these situations, we will have access to the Personal Information that you have provided to such social media account. Please note that if you choose to connect your social media contacts and address book information with us, we may collect contact information for your listed friends pursuant to the terms of your social media account. In such case, you represent and warrant that you are authorized to provide us with all such contact information and are in compliance with your agreements with any such social media accounts.</p>
            <p align="justify">&nbsp;2.11&nbsp;We may also obtain information from other sources and combine that with information we collect directly. For example, we may collect information about you from third parties, including but not limited to identity verification services, fraud detection service providers, credit bureaus, mailing list providers and publicly available sources. If you create or log into your account through a social media site, we will have access to certain information from that site, such as your name, account information and friends lists, in accordance with the authorization procedures determined by such social media site. </p>
            <p align="justify">&nbsp;2.12&nbsp;We may also use third party services, such as Google Analytics, to track and analyze online behavior data of users. If you would like to opt out of Google Analytics, please download and install the browser plugin at <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>. Users can also opt out of third party interest based advertising by visiting the Network Advertising Initiative’s deactivation website at <a href="www.networkadvertising.org/choices/">www.networkadvertising.org/choices/</a>. </p>
            <p align="justify">&nbsp;2.13&nbsp;<u>Other Collection Methods:</u>  If you choose to use our referral service to tell a friend about our Site(s), we will ask you for your friend’s name and email address. We will automatically send your friend an email inviting him/her to visit the Site(s). We may send up to three (3) follow up emails. RTF LIVE stores this information for the purpose of sending this email(s) and tracking the success of our referral program. <p align="justify">&nbsp;2.12&nbsp;We may also use third party services, such as Google Analytics, to track and analyze online behavior data of users. If you would like to opt out of Google Analytics, please download and install the browser plugin at <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>. Users can also opt out of third party interest based advertising by visiting the Network Advertising Initiative’s deactivation website at <a href="www.networkadvertising.org/choices/">www.networkadvertising.org/choices/</a>. </p></p>
            <p align="justify">&nbsp;2.14&nbsp;Some features of the Services allow you to provide content to the Services, such as video clips. All content submitted by you to the Services may be retained by us indefinitely, even after you terminate your Account. We may continue to disclose such content to third parties in a manner consistent with this Privacy Policy. </p>
            <p align="justify">&nbsp;2.15&nbsp;We may communicate with you via push notification, Whatsapp, email, SMS, MMS or other text message (to the extent you permit us to do so), and we may collect information regarding such communications, including, without limitation, confirmation when you open an email, read a message or receive a push notification.  By registering for RTF LIVE, you agree to receive automated promotional text messages and Whatsapp messages from or on behalf of RTF LIVE.  You are not required to provide this consent as a condition of purchasing any property, goods or services.  Standard messaging rates may apply.  Some of your activity on and through the Services is public. This may include, but is not limited to, content you have posted publicly on, through or in connection with the Services, including without limitation on public portions of third party services, such as social media platforms. </p>
            <p align="justify"><strong>3.&nbsp;<u>How We Use Your Information.</u></strong> </p>
            <p align="justify">We may use the Personal Information we collect for various purposes, including to:<br/></p>
            <ul><li>personalize and tailor the features, performance and support of the Site(s)</li><li>send you promotional/marketing information, newsletters, offers or other information from us or on behalf of our sponsors or partners</li><li>perform internal operations, including fraud detection</li><li>analyze, benchmark and conduct research on user data and interactions with the Services</li><li>authenticate users</li><li>provide the materials, goods and/or services we offer and/or you request</li><li>enable you to participate in features such as sending and receiving invitations, surveys, reviews, blogs or forums, or to participate in special initiatives and to communicate with you about them</li><li>complete your ticket redemption and/or any purchase transactions, fulfill your orders, keep you informed about the status of our goods and services and your orders </li><li>identify your product and service preferences, so we can notify you of new or additional products, services, and promotions that might be of interest to you </li><li>conduct market research and to customized offers;</li><li>improve our services and any merchandise selections, customer service, and overall Site(s) experience by aggregating and analyzing our customer data</li><li>analyze the use of our products and services and information about visitors to the Site(s) to enhance our marketing efforts</li><li>update and maintain the accuracy of information about our customers</li><li>communicate with you by email, text message, app notifications, or other means about our company, our products, or other information that we believe may be of interest to you </li><li>provide others with your Personal Information for the limited purposes described in this Privacy Policy</li><li>if you join our electronic mailing list, to send you our electronic communications, including our newsletters and our company announcements, alerts, notices and updates </li><li>send you notices of a transactional, administrative or relationship nature or as required by law. </li></ul>
            <br></br>
            <br/>
            We may use the Anonymous Information we collect for various purposes, including to:
            <br></br>
            <ul><li>perform internal operations on the Site(s)</li><li>improve the Site(s) and customize the user experience</li><li>aggregate the information collected via Cookies and Pixels to use in statistical analysis to help us track trends and analyze patterns</li></ul>
            <p></p>
            <p align="justify"><strong>&nbsp;4.	How We Share and Disclose Information with Third Parties.    </strong></p>
            <p align="justify">&nbsp;4.1&nbsp;We know how important it is to keep your information confidential. We will not rent, sell, or share your Personal Information with third parties, except as set forth herein. </p>
            <p align="justify">&nbsp;4.2&nbsp;If you do not want us to use or disclose Personal Information collected about you in the ways identified in this Privacy Policy, you may choose not to use Site(s), or provide your Personal Information at any time. </p>
            <p align="justify">&nbsp;4.3&nbsp;We may disclose your Personal Information to outside individuals and/or companies that help us bring you the products and services we offer and to create, operate, and maintain our Website. For example, we may work with third parties to: (a) manage a database of customer information; (b) assist us in distributing e-mails; (c) assist us with direct marketing and data collection; (d) provide data storage and analysis; (e) provide fraud prevention; (f) provide customer service; and (g) provide other services designed to assist us in developing and running our Website and maximizing our business potential. We require that these outside companies agree to keep all information shared with them confidential and to use the information only to perform their obligations to us. </p>
            <p align="justify">&nbsp;4.4&nbsp;You agree to allow us to share your geo-location information.</p>
            <p align="justify">&nbsp;4.5&nbsp;We may disclose information we have collected about you if required to do so by law or if we, in our sole discretion, believe that disclosure is reasonable to: (i) satisfy any applicable law, regulation, legal process or governmental request; (ii) enforce this Privacy Policy and our Terms of Use, including investigation of potential violations hereof; (iii) detect, prevent, or otherwise address fraud, security or technical issues; (iv) respond to user support requests; or (v) protect our rights, property or safety, our users and the public. This includes exchanging information with other companies and organizations for fraud protection and spam/malware prevention. </p>
            <p align="justify">&nbsp;4.6&nbsp;<u>Aggregate Anonymous Information:</u> Aggregated Anonymous Information is the combination of your Anonymous Information with the Anonymous Information of other Users (“Aggregated Anonymous Information”). Aggregated Anonymous Information does not allow you to be identified or contacted. We may share such Aggregated Anonymous Information with third parties. </p>
            <p align="justify">&nbsp;4.7&nbsp;We may share your Personal Information with any of our subsidiaries, joint venturers, or other companies under common control, in which case we will require them to honor this Privacy Policy. Additionally, in the event we undergo a business transition such as a merger, acquisition by another company, or sale of all or a portion of our assets, your Personal Information may be among the assets transferred, and your Personal Information may be shared as part of the negotiation of the transaction. You acknowledge that such transfers may occur and are permitted by this Privacy Policy, and that any entity that acquires us, is merged with us or that acquires our assets may continue to process your Personal Information as set forth in this Privacy Policy.</p>
            <p align="justify"><strong>&nbsp;5.&nbsp;Non-Personally Identifiable Information.</strong></p>
            <p align="justify">&nbsp;5.1&nbsp;Through your use of the Site(s), we may also collect certain non-personally identifiable information from you (“NPII”). NPII is not associated with you as an individual. It is measured anonymously and only in the aggregate. We use NPII to maintain and administer the Site(s), analyze trends, gather demographic information and comply with applicable law. We may share this information with others without express notice to you or consent from you, and we may exploit, use and disclose your NPII without limitation of any kind. </p>
            <p align="justify">&nbsp;5.2&nbsp;The Site(s) may use cookies. A cookie is a small piece of information sent by a Site(s) that is saved on your hard drive by your computer's browser. Cookies help us remember you when you return to the Site(s). Cookies also hold information to personalize and enhance your experience and to gather Site(s) statistical data, such as which pages are visited, the Internet provider's domain name and the addresses of the sites you visited immediately before coming to and immediately after leaving the Site(s). The information in the cookies lets us trace your "clickstream" activity (i.e., the paths taken by users of the Site(s) as they move from page to page) to enable us to better serve you by revealing which portions of the Site(s) are the most popular. We may also allow our affiliate and service providers and advertisers to serve cookies from the Site(s) to allow them to assist us in various activities such as doing analysis and research on the effectiveness of the Site(s), its content and advertising. Some third party advertising companies may be advertising networks that are members of the Network Advertising Initiative, which offer a single location to opt out of ad targeting from member companies. For more information, see: <a href="www.networkadvertising.org">www.networkadvertising.org</a>.  </p>
            <p align="justify">&nbsp;5.3&nbsp;We may also use "pixel tags" (sometimes called "web beacons" or "clear gifs"), which are tiny graphic images, on the Site(s). Pixel tags help us analyze users’ online behavior and measure the effectiveness of the Site(s) and our advertising and marketing. Pixel tags or Clear gif files are tiny graphics with a unique label that work in a similar way to cookies and are used to monitor the user’s online activities. In contrast to cookies that are saved on a user’s computer hard disk, clear gif files are embedded invisibly in websites and are about as big as the full stop at the end of this sentence. Where appropriate, we may combine the information collected by such pixel tags with the Personal Information of our customers. We may also use other analytical tools to evaluate site performance through the use of aggregated data, which contain no Personal Information. We work with service providers that help us track, collect, and analyze this information. </p>
            <p align="justify">&nbsp;5.4&nbsp;Cookies, pixel tags, and/or other analytical tools that we may use on the Site(s) may collect information about your visit, including the pages you view, the features you use, the links you click, and other actions you take in connection with the Site(s). This information may include your computer's Internet protocol (IP) address, your browser type, your operating system, date and time information, and other technical information about your computer. We may also track certain information about the identity of the Site(s) you visited immediately before coming to the Site(s). Cookies, pixel tags, and/or other analytical tools in our emails may also be used to track your interactions with those messages, such as when you receive, open, or click a link in an email message from us. We may also work with businesses that use tracking technologies to deliver advertisements on our behalf across the Internet. These companies may collect information about your visits to the Site(s) and your interaction with our advertising and other communications, but no Personal Information is shared with them. </p>
            <p align="justify">&nbsp;5.5&nbsp;We may combine the NPII collected through cookies, pixel tags and other analytical tools with other information we may have collected from you. This information may be used to improve the Site(s), to personalize your online experience, to help us deliver information to you, to determine the effectiveness of advertising, and for other internal business purposes. We may use and share aggregated and anonymous information to conduct market research and analysis for ourselves and/or for our business partners. Given the anonymous, non-personally identifiable nature of such information, there are no restrictions under this Privacy Policy on how we may use or disclose such information. For example, we may freely share such information with third parties who may use such data for their own marketing, advertising, research, or other business purposes. We may also freely share such information with our service providers in order for them to perform services to or for us. </p>
            <p align="justify">&nbsp;5.6&nbsp;We authorize certain service providers to utilize NPII for their business purposes and in accordance with their privacy policies, such as to report on usage or industry trends to their customer base.  </p>
            <p align="justify">&nbsp;5.7&nbsp;Third Party Functionalities: The Site(s) contains links to and/or enables certain third party functionalities to enhance your experience on the Site(s), including social plug-ins, tools and APIs. Prior to using any third party functionalities (e.g., Facebook “Like” button) on the Site(s), you should consult the privacy notices of the third party providers of such functionalities (e.g., Facebook), as we have no control over information that is submitted to, or collected by, such third parties, or how they may use the information. The privacy policies and data practices of such third parties may significantly differ from ours, and we make no representation or warranty whatsoever about their policies and practices. Your communications and interactions with such third parties are solely between you and them, and are at your own risk.</p>
            <p align="justify"><strong>&nbsp;6.&nbsp;<u>Your Choices/Opt-Out.</u></strong></p>
            <p align="justify">&nbsp;6.1&nbsp;You consent to receive certain communications from us. You may opt out of: (a) receiving email communications such as email newsletters and promotional emails by following the instructions provided at the bottom of each email, clicking the “unsubscribe” button at the bottom of emails we sent you; and/or (b) receiving promotional email communications and newsletters by emailing us at <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a> and including the word “UNSUBSCRIBE” in the subject text. Please allow up to ten (10) business days for changes to your email preferences to take effect. During that time, you may continue to receive email communications from us that were already in process. Opting out of receiving Site(s) communications will not affect your receipt of service-related communications, such as payment confirmations and delivery status updates, as we must be able to communicate with you regarding your purchases. </p>
            <p align="justify">&nbsp;6.2&nbsp;Opting out of online and mobile website advertising. You can opt out of Internet-based and mobile advertising on your mobile device by visiting TRUSTe’s Ad Preference Manager, currently available at <a href="https://preferences-mgr.truste.com/">https://preferences-mgr.truste.com/</a>.  </p>
            <p align="justify">&nbsp;6.3&nbsp;Our products and services may use Google Analytics Advertising Features and its associated tracking technologies to help display our ads you see on other sites, and to help us manage and optimize our online advertising efforts. To opt out of Google Analytics Advertising Features, visit Google’s Ad Settings page, currently located at <a href="https://www.google.com/settings/ads/anonymous?sig=ACi0TChBBUZhbil6jSzh_t9gc_hilJmxPFILo3fzsOJJ6mtq1DpanjQIychv5x00ayD5xiJnE_7py3LRuGOQtj8YQx5_1ZS2FA&amp;hl=en">https://www.google.com/settings/ads/anonymous?sig=ACi0TChBBUZhbil6jSzh_t9gc_hilJmxPFILo3fzsOJJ6mtq1DpanjQIychv5x00ayD5xiJnE_7py3LRuGOQtj8YQx5_1ZS2FA&amp;hl=en</a>. Website users can also access the Google Analytics Opt Out Browser Add-on, currently located at <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a> or <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>. We may also work with Facebook and Apple to provide analytics in connection with our Site(s), including our mobile applications. For more information about Facebook’s privacy practices, you may visit <a href="https://www.facebook.com/about/privacy">https://www.facebook.com/about/privacy</a>, and for Apple’s privacy policy, click here <a href="http://www.apple.com/privacy/privacy-policy/">http://www.apple.com/privacy/privacy-policy/</a>.   </p>
            <p align="justify">&nbsp;6.4&nbsp;You may can opt out of receiving online behavioral or internet based advertising by using the tools located at the Digital Advertising Alliance’s consumer choice page, currently available at http://www.aboutads.info/choices/ or the Network Advertising Initiative (NAI) opt out tool currently available at <a href="http://www.networkadvertising.org/choices/">http://www.networkadvertising.org/choices/</a>.   </p>
            <p align="justify">&nbsp;6.5&nbsp;When using the ad industry opt out tools described in Sections 6.2 through 6.4, note that: (a) if you opt-out we may still collect some data about your online activity for operational purposes (such as fraud prevention), but it will not be used by us for the purpose of targeting ads to you; (b) if you use multiple browsers or devices you may need to execute this opt out on each browser or device; and (c) other ad companies’ opt-outs may function differently than our opt-out, and we have no control over the practices of any third parties. We do not make any representations or warranties about such opt-out services. Such services are independent from us, and we have no control over, or responsibility for their performance.</p>
            <p align="justify">&nbsp;6.6&nbsp;You can opt out of accepting cookies or disable them from your browser. The “Help” function on most browsers contains information on how you can set your browser to notify you before accepting cookies, or can disable them entirely. If you opt out of cookies, you will not be able to take advantage of various features of the Site(s) that are available to other users. For example, we may use cookies to recognize you by name when you return to this site so you don’t have to login again and provide your password each time.  </p>
            <p align="justify">&nbsp;6.7&nbsp;If you prefer not to receive text or wireless promotional communications on your mobile device, you can opt out by replying STOP to any text you receive from us. </p>
            <p align="justify">&nbsp;6.8&nbsp;You may ask us to delete your Personal Information from our system, however, because we archive and keep track of past transactions, you cannot delete information associated with past transactions or archived information on the Site(s). Please also update your Personal Information if it changes. </p>
            <p align="justify">&nbsp;6.9&nbsp;Registered users may terminate their account registration at any time, for any reason, by contacting us. Terminating your account registration will not necessarily remove previous public comments or other user content on public display on the Site(s). You understand it may be impossible to delete Personal Information entirely because of backups and records of deletions. Further, please note that we may be required to maintain certain Personal Information, or to maintain certain Personal Information for a period of time, in which case we will comply with your deletion request only after we have fulfilled such requirements. When we delete any information, it will be deleted from our active database, but may remain in our archives. We may retain your information for fraud detection or similar purposes. Note that if we have already disclosed some of your Personal Information to third parties, we cannot access that Personal Information any longer and cannot compel the deletion or modification of any such information by the parties to whom we have made those disclosures. If you wish to cancel your account on the Site(s) or delete your Personal Information previously provided to us, you may send your request to us at <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a> and include the words “DELETE ME” in the subject line with your specific request in the body of your communication.  </p>
            <p align="justify">&nbsp;6.10&nbsp;If you do not receive a response from us to any emails you send to us within ten (10) business days, please send us another email as your original email may not have been received. </p>
            <p align="justify">&nbsp;6.11&nbsp; Please note that despite any indicated marketing preferences, we may send you administrative emails regarding the Site(s), including, for example, notices of updates to our Privacy Policy.  </p>
            <p align="justify"><strong>&nbsp;7.&nbsp;<u>Your Security.</u></strong></p>
            <p align="justify">&nbsp;7.1&nbsp;We strive to keep your Personal Information private and safe. We take commercially reasonable physical, electronic and administrative steps to maintain the security of Personal Information collected, including limiting the number of people who have physical access to database servers, as well as employing electronic security systems and password protections that guard against unauthorized access. In addition, it is our policy to never send your credit card number via e-mail. Any payment transactions will be encrypted. </p>
            <p align="justify">&nbsp;7.2&nbsp;Unfortunately, despite our best efforts, the transmission of data over the Internet cannot be guaranteed to be 100% secure. While we will use reasonable means to ensure the security of information you transmit through the Site(s), any transmission of Personal Information is at your own risk. We cannot guarantee that such information will not be intercepted by third parties and we shall not be liable for any breach of the security of your Personal Information resulting from causes or events that are beyond our control, including, without limitation, your own act or omission, corruption of storage media, defects in third party data security products or services, power failures, natural phenomena, riots, acts of vandalism, hacking, sabotage, or terrorism, and we are not responsible for circumvention of any privacy settings or security measures contained on the Site(s).  </p>
            <p align="justify">&nbsp;7.3&nbsp;We will make any legally required disclosures of any breach of the security, confidentiality, or integrity of your unencrypted electronically stored "personal data" (as defined in applicable state statutes on security breach notification) to you via email and/or conspicuous posting on the Site(s) in the most expedient time possible and without unreasonable delay, insofar as it is consistent with (i) the legitimate needs of law enforcement; or (ii) any measures necessary to determine the scope of the breach and restore the reasonable integrity of the data system.  </p>
            <p align="justify"><strong>&nbsp;8.&nbsp;<u>Links to Other Site(s).</u></strong></p>
            <p align="justify">&nbsp;8.1&nbsp;While visiting the Site(s), you may link to websites operated by third parties or you may have come to the Site(s) using a link found in another website. This does not mean that we endorse these Site(s) or the goods or services they provide. We do not make any representations or warranties about any Site(s) that may be linked to the Site(s). Such other Site(s) are independent from us, and we have no control over, or responsibility for their information, products or activities.</p>
            <p align="justify">&nbsp;8.2&nbsp;In addition, our privacy practices may differ from those of these other Site(s). If you provide Personal Information at one of those Site(s), you are subject to the privacy policy of the operator of that Site(s), not our Privacy Policy. Please make sure you understand any other website's privacy policy before providing Personal Information. </p>
            <p align="justify"><strong>&nbsp;9.&nbsp;<u>Children</u></strong></p>
            <p align="justify">This Site(s) is not directed to or intended for children under 13 years of age. We do not knowingly solicit, collect or maintain information from those we actually know are under 13 years of age, and no part of our Site(s) is targeted to attract anyone under 13 years of age. We also do not send e-mail correspondence to anyone who advises that they are under the age of 13 years of age. If we later obtain actual knowledge that a User is under 13 years of age we will take steps to remove that User’s Personal Information from our systems. If you are the parent or guardian of a child whom you believe has disclosed Personal Information to us, please contact us at <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a>. so that we may delete and remove such information from our system. </p>
            <p align="justify"><strong>&nbsp;10.&nbsp;<u>Changes to Our Privacy Policy.</u></strong></p>
            <p align="justify">We reserve the right to change, modify, add or remove portions of this Privacy Policy at any time and without prior notice, and any changes will become effective immediately upon being posted unless we advise you otherwise. However, we will not use your Personal Information in a way that is adverse and materially different from the uses described in this Privacy Policy without giving you an opportunity to opt out. Your continued use of the Site(s) after this Privacy Policy has been amended shall be deemed to be your continued acceptance of the terms and conditions of the Privacy Policy, as amended. We encourage you to review this Privacy Policy regularly.</p>
            <p align="justify"><strong>&nbsp;11.&nbsp;<u>California Privacy Rights.</u></strong></p>
            <p align="justify">&nbsp;11.1&nbsp;Under California Civil Code sections 1798.83-1798.84, California residents are entitled to ask us for a notice describing what categories of Personal Information we share with third parties or corporate affiliates for those third parties or corporate affiliates' direct marketing purposes. That notice will identify the categories of information shared and will include a list of the third parties and affiliates with which it was shared, along with their names and addresses. If you are a California resident and would like a copy of this notice, please submit an email request to the following email address: amit.raut@rtflive.com and include the words “CALIFORNIA PRIVACY” in the subject line, and you must put the statement “Your California Privacy Rights” in the body of the request and state the name of our specific website with respect to which you are requesting the information as well as your name, street address, city, state, and zip code. </p>
            <p align="justify">&nbsp;11.2&nbsp;In addition, please note the following:  </p>
            <p align="justify">&nbsp;&nbsp;(a)&nbsp;Users can visit the Site(s) anonymously;  </p>
            <p align="justify">&nbsp;&nbsp;(b)&nbsp;We will add a link to this Privacy Policy on our home page, or at a minimum, on the first significant page after entering the Site(s);</p>
            <p align="justify">&nbsp;&nbsp;(c)&nbsp;Our Privacy Policy link includes the word “Privacy” and can be easily be found on the page specified above; </p>
            <p align="justify">&nbsp;&nbsp;(d)&nbsp;Users will be notified of any privacy policy changes on our Privacy Policy page; </p>
            <p align="justify">&nbsp;&nbsp;(e)&nbsp;Users are able to change their Personal Information by emailing us or by calling us;</p>
            <p align="justify">&nbsp;&nbsp;(f)&nbsp;Some Internet browsers include the ability to transmit “Do Not Track” signals that give you control over the collection and use of web browsing information. Because uniform standards for “Do Not Track” signals have not yet been adopted, we do not process or respond to such signals in users’ web browsers at this time; and </p>
            <p align="justify">&nbsp;&nbsp;(g)&nbsp;We allow the collection of users’ behavioral tracking (but not Personal Information) by third parties. We do not authorize the collection of Personal Information on the Site(s) by third parties. </p>
            <p align="justify"><strong>&nbsp;12.&nbsp;<u>Disclosure for Legal Purposes. </u></strong></p>
            <p align="justify">You hereby authorize us to disclose any of your Personal Information pursuant to judicial and administrative proceedings and to law enforcement or government agencies if we believe the disclosure is necessary or appropriate. You also authorize us to disclose Personal Information if we believe the disclosure is necessary or appropriate in the event of an investigation of fraud, improper or illegal conduct in connection with the Site(s), such as fraud, misrepresentation, intellectual property infringement, or other activity that may put us at risk for liability.</p>
            <p align="justify"><strong>&nbsp;13.&nbsp;<u>Non-Confidential Information. </u></strong></p>
            <p align="justify">We do not want you to send to us any confidential or proprietary information through email or otherwise. Any information, materials, suggestions, ideas or comments sent to us will be considered non-confidential, and by submitting the same to us, you are giving us the absolute right to use, modify, reproduce, transmit, display and distribute the information for any purpose whatsoever, with no payment or other compensation to you. However, we will not use your name unless we are required by law to identify the source of the materials, information, suggestions, ideas or comments, or unless we first obtain your permission.</p>
            <p align="justify"><strong>&nbsp;14.&nbsp;<u>Assignment </u></strong></p>
            <p align="justify">We may freely assign this Privacy Policy or any of our rights and/or obligations hereunder.</p>
            <p align="justify"><strong>&nbsp;15.&nbsp;<u>Disputes.</u></strong></p>
            <p align="justify">&nbsp;15.1&nbsp;This Privacy Policy will be interpreted in accordance with the laws of the State of New York and the United States of America, without regard to its conflict-of-law provisions. By visiting the Site(s), you agree that, except as otherwise specified herein, the laws of the State of New York without regard to principles of conflict of laws, will govern any dispute of any sort that might arise between us or any of our affiliates regarding your visit and use of the Site(s) and Services.</p>
            <p align="justify">&nbsp;15.2&nbsp;We and you agree that in the event of any dispute, the party wishing to address the dispute must contact the other party in writing, including by e-mail, and advise the other party of the dispute in reasonable detail as well as informing the other party of the remedy being sought. We may send you notices via the email address or physical address you provide to us, and all notices to us shall be sent to the following email address: <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a> and include the words “DISPUTE NOTICE” in the subject. The parties shall then make a good faith effort to resolve the dispute before resorting to more formal means of resolution. In the event that the dispute is not resolved through this procedure, the party raising the dispute may proceed to mandatory arbitration as set forth below. </p>
            <p align="justify">&nbsp;15.3&nbsp;ANY AND ALL DISPUTES BETWEEN YOU AND US WILL BE RESOLVED BY BINDING ARBITRATION. YOU HEREBY AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this Privacy Policy, except for matters that may be taken to small claims court. Your rights will be determined by a neutral arbitrator, NOT a judge or jury. You agree that any dispute arising out of or relating to this Privacy Policy, including with respect to the interpretation of any provision of this Privacy Policy or other agreements between you and us, or concerning the performance or obligations of you and us, shall be resolved by mandatory and binding arbitration submitted to JAMS in accordance with its Commercial Arbitration Rules at the request of either us or you pursuant to the following conditions:</p>
            <p align="justify">&nbsp;15.4&nbsp;Place of Arbitration Hearings. Unless you elect to conduct the arbitration by telephone or written submission, an in-person arbitration hearing will conducted at a JAMS facility in your area or at a JAMS facility in New York, New York.</p>
            <p align="justify">&nbsp;15.5&nbsp;Selection of Arbitrator shall be made pursuant to JAMS’ Streamlined Arbitration Rules &amp; Procedures or JAMS’ Comprehensive Arbitration Rules &amp; Procedures, depending on the amount of the claim as specified herein.</p>
            <p align="justify">&nbsp;15.6&nbsp;Conduct of Arbitration. The arbitration shall be conducted by a single neutral arbitrator under JAMS’ Streamlined Arbitration Rules &amp; Procedures. For claims exceeding $5,000.00, the arbitration shall be conducted under JAMS’ Comprehensive Arbitration Rules &amp; Procedures Subject to the applicable JAMS procedure, the arbitrator shall allow reasonable discovery in the forms permitted by the Federal Rules of Civil Procedure, to the extent consistent with the purpose of the arbitration. The arbitrator(s) shall have no power or authority to amend or disregard any provision of this section or any other provision of these Terms of Use, except as necessary to comply with JAMS’ Policy on Consumer Arbitrations Pursuant to Pre-Dispute Clauses Minimum Standards of Procedural Fairness. The arbitration hearing shall be commenced promptly and conducted expeditiously. If more than one day is necessary, the arbitration hearing shall be conducted on consecutive days unless otherwise agreed in writing by the parties.</p>
            <p align="justify">&nbsp;15.7&nbsp;Findings and Conclusions. The arbitrator(s) shall, after reaching judgment and award, prepare and distribute to the parties written findings of fact and conclusions of law relevant to such judgment and award and containing an opinion setting forth the reasons for the giving or denial of any award. The award of the arbitrator(s) shall be final and binding on the parties, and judgment thereon may be entered in a court of competent jurisdiction.<p align="justify">&nbsp;15.6&nbsp;Conduct of Arbitration. The arbitration shall be conducted by a single neutral arbitrator under JAMS’ Streamlined Arbitration Rules &amp; Procedures. For claims exceeding $5,000.00, the arbitration shall be conducted under JAMS’ Comprehensive Arbitration Rules &amp; Procedures Subject to the applicable JAMS procedure, the arbitrator shall allow reasonable discovery in the forms permitted by the Federal Rules of Civil Procedure, to the extent consistent with the purpose of the arbitration. The arbitrator(s) shall have no power or authority to amend or disregard any provision of this section or any other provision of these Terms of Use, except as necessary to comply with JAMS’ Policy on Consumer Arbitrations Pursuant to Pre-Dispute Clauses Minimum Standards of Procedural Fairness. The arbitration hearing shall be commenced promptly and conducted expeditiously. If more than one day is necessary, the arbitration hearing shall be conducted on consecutive days unless otherwise agreed in writing by the parties.</p></p>
            <p align="justify">&nbsp;15.8&nbsp;Costs and Fees. You will be subject to a filing fee, set by JAMS, to initiate the arbitration. To the extent permitted by JAMS procedures, each party shall bear its own costs and expenses and an equal share of the arbitrators’ and administrative fees of arbitration, and we will remain responsible for its share of costs, expenses and fees plus any costs, expenses and fees required under JAMS procedures.</p>
            <p align="justify">&nbsp;15.9&nbsp;Litigation. The Federal Arbitration Act and federal arbitration law apply to these Terms. Either party also may, without waiving any remedy under these Terms, seek from any court having jurisdiction any interim or provisional relief that is necessary to protect the rights or property of that party, pending the establishment of the arbitral tribunal (or pending the arbitral tribunal’s determination of the merits of the controversy).</p>
            <p align="justify">&nbsp;15.10&nbsp;Notwithstanding the arbitration clause herein, the parties also agree that we may bring suit in a court located in New York, New York, to enjoin infringement or other misuse of our intellectual property rights.</p>
            <p align="justify">&nbsp;15.11&nbsp;Other. The Federal Arbitration Act and federal arbitration law apply to this Privacy Policy. Both you and we expressly waive any ability to maintain any class action proceedings in any forum.</p>
            <p align="justify"><strong>&nbsp;16.&nbsp;<u>Class-Action Waiver.</u></strong></p>
            <p align="justify">Any arbitration, claim or other proceedings by or between you and us shall be conducted on an individual basis and not in any class action, mass action, or on a consolidated or representative basis. You further agree that the arbitrator shall have no authority to award class-wide relief or to combine or aggregate similar claims or unrelated transactions. You acknowledge and agree that this agreement specifically prohibits you from commencing arbitration proceedings as a representative of others. If for any reason a claim proceeds in court rather than in arbitration, each party waives any right to a jury trial. Any claim that all or part of this Class Action Waiver is unenforceable, unconscionable, void, or voidable may be determined only by a court of competent jurisdiction and not by an arbitrator.</p>
            <p align="justify"><strong>&nbsp;17.&nbsp;<u>Contact Us.</u></strong></p>
            <p align="justify">If you have any questions regarding our Privacy Policy, you can contact us via email at <a href="mailto:amit.raut@rtflive.com">amit.raut@rtflive.com</a> or write to us at RTF LIVE, 159-16 Union Turnpike Suite 212, Fresh Meadows, NY 11366.</p>
            <p align="justify"><strong>Last updated Dec 15, 2020</strong></p>



</div>
</div>
</div>

</div>
<Footer/>
</>
)
}
